export const dishImages: Record<string, string> = {
  "Omlet povrće": "/images/dishes/omlet_povrce.png",
  "Omlet sa sirom": "/images/dishes/omlet_sir.png",
  "Doručak za dvoje": "/images/dishes/dorucak_za_2.png",
  "Engleski doručak": "/images/dishes/engleski_dorucak.png",
  "Punjene prženice": "/images/dishes/punjene_przenice.png",
  "Slani uštipci": "/images/dishes/ustipci_slani.png",
  "Kačamak": "/images/dishes/kacamak.png",
  "Cezar tortilja": "/images/dishes/cezar_tortilja.png",
  "Burito": "/images/dishes/burito.png",
  "Carbonara": "/images/dishes/carbonara.png",
  "Mrsni brusketi": "/images/dishes/mrsni_brusketi.png",
  "Posni brusketi": "/images/dishes/posni_brusketi.png",
  "Daska": "/images/dishes/daska.png",
  "Classic burger": "/images/dishes/classic_burger.png",
  "Chicken burger": "/images/dishes/chicken_burger.png",
  "Rižoto sa piletinom": "/images/dishes/rizoto_piletina.png",
  "Rižoto sa povrćem": "/images/dishes/rizoto_povrce.png",
  "Potaž od povrća": "/images/dishes/potaz.png",
  "Teleća čorba": "/images/dishes/teleca_corba.png",
  "Pohovani pileći štapići": "/images/dishes/pohovani_stapici.png",
  "Fitnes piletina": "/images/dishes/fitnes_piletina.png",
  "Pileći medaljoni": "/images/dishes/piletina_medaljoni.png",
  "Slatko-ljuta piletina": "/images/dishes/slatko_ljuta.png",
  "Ramstek": "/images/dishes/ramstek.png",
  "Piletina u sosu od pečuraka": "/images/dishes/piletina_pecurke.png",
  "Pljeskavica": "/images/dishes/pljeskavica.png",
  "Ćevapi": "/images/dishes/cevapi.png",
  "Bečka šnicla": "/images/dishes/backa_snicla.png",
  "Capricciosa": "/images/dishes/capricciosa.png",
  "San Giovanni": "/images/dishes/san_giovanni.png",
  "Margarita": "/images/dishes/margarita.png",
  "Idolo pica": "/images/dishes/idolo_pizza.png",
  "Cezar salata": "/images/dishes/cezar_salata.png",
  "Tuna salata": "/images/dishes/tuna_salata.png",
  "Ramstek salata": "/images/dishes/ramstek_salata.png",
  "Šopska salata": "/images/dishes/shopska.png",
  "Pomfrit 300 g": "/images/dishes/pomfrit.png",
  "Vedžis 300 g": "/images/dishes/vedzis.png",
  "Pohovani luk 300 g": "/images/dishes/pohovani_luk.png",
  "Grilovano povrće": "/images/dishes/grilovano_povrce.png",
  "Cheese cake": "/images/dishes/cheesecake.png",
  "Idolo torta": "/images/dishes/idolo_torta.png",
  "Čokoladni tart sa kremom od pistaća i sladoledom od vanile": "/images/dishes/cokoladni_tart.png",
  "Slatke palačinke": "/images/dishes/palacinke.png",
  "Belvi kup": "/images/dishes/belvi_kup.png",
  "Palačinke sa sladoledom": "/images/dishes/palacinke_sladoled.png",
  "Palačinke sa pistać kremom i nutelom": "/images/dishes/pistaci_palacinke.png",
  "Mojito": "/images/dishes/mojito.png",
  "Aperol Spritz": "/images/dishes/aperol.png",
};

export function getDishImage(name: string): string | undefined {
  return dishImages[name];
}
