export const images = {
  logo: "/images/logo.png",
  logoHeader: "/images/logo-header.png",
  poweredByLogo: "/images/cokoladni-ajti-logo.png",
  hero: "/images/hero-steak-salad.png",
  heroCoffee: "/images/hero-coffee.png",
  about: "/images/about-spread.png",
  contact: "/images/gallery-outdoor.png",
  gallery: [
    { src: "/images/gallery-interior.png", alt: "Enterijer Idolo Bistro Bar" },
    { src: "/images/gallery-terrace.png", alt: "Bašta i terasa" },
    { src: "/images/gallery-outdoor.png", alt: "Ambijent na otvorenom" },
    { src: "/images/gallery-coffee-girl.png", alt: "Kafa u Idolu" },
    { src: "/images/gallery-table-spread.png", alt: "Hrana na stolu" },
    { src: "/images/gallery-cocktail.png", alt: "Kokteli i piće" },
    { src: "/images/gallery-cheesecake.png", alt: "Dezerti" },
    { src: "/images/gallery-caesar.png", alt: "Salate i paste" },
    { src: "/images/gallery-gelato.png", alt: "Detalji serviranja" },
    { src: "/images/gallery-rolls.png", alt: "Bistro kuhinja" },
    { src: "/images/menu-pizza.png", alt: "Pizza" },
    { src: "/images/menu-breakfast.png", alt: "Doručak" },
  ],
  menu: {
    pizza: "/images/menu-pizza.png",
    dorucak: "/images/menu-breakfast.png",
    piletina: "/images/menu-schnitzel.png",
    sendvici: "/images/menu-sandwich.png",
    rostilj: "/images/menu-grill.png",
    pasta: "/images/menu-pasta.png",
    palačinke: "/images/menu-crepes.png",
  },
} as const;
